import { useQuery } from '@apollo/client';
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { Layout } from '../components/Layout';
import { ProductCard } from '../components/ProductCard';
import TopBar from '../components/TopBar';
import {
  PromotionQueryDocument,
  PromotionQueryQuery,
} from '../generated/graphql';

type ProductCard = {
  id: string;
  stock?: number | null;
  price?: number | null;
  newProduct?: boolean | null;
  onDiscount?: boolean | null;
  promotion?: boolean | null;
  title: string;
  slug?: string | null;
  subtitle?: string | null;
  discountPercent?: number | null;
  images?: {
    __typename?: 'Asset';
    url: string;
  } | null;
  warranty?: number | null;
};

const Home: NextPage = () => {
  const { data, loading, error } = useQuery<PromotionQueryQuery>(
    PromotionQueryDocument
  );
  if (loading) {
    <div>loading...</div>;
  }
  if (error) {
    <div>エラーです。</div>;
  }

  const topBarTitle = 'New & Promo Products';

  type PromotionQueryType = Omit<PromotionQueryQuery, '__typename'>;

  function maphoge(data: PromotionQueryQuery): PromotionQueryType {
    const returnedTarget = Object.assign({}, data); //dataのクローンを作る
    delete returnedTarget.__typename; //__typenameを削除
    return returnedTarget;
  }
  // console.log('maphoge', data);

  const _data = data ? maphoge(data) : null;
  const productList = _data ? Object.values(_data) : [];
  // console.log('productList', productList);

  let myItems: ProductCard[] = [];

  productList.map((items) => {
    // console.log('items', items);

    items.map((item) => {
      return myItems.push(item);
    });
  });

  // console.log(myItems);

  const productCards = myItems.map((item) => (
    <Link href={`/products/${item.slug}`} key={item.id}>
      <a>
        <ProductCard item={item} />
      </a>
    </Link>
  ));

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="main-container">
          <div className="main-product-section">
            <TopBar title={topBarTitle} />
            <div className="product-card">{productCards}</div>
          </div>
        </div>
      </Layout>
    </>
  );
};

export default Home;
